version: "3.9"

services:
  common:
    image: moneytrackr-common
    build:
      context: ./MoneyTrackr/Common
  api:
    image: rolandomalena/moneytrackr:api-production
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Api
  web:
    image: rolandomalena/moneytrackr:web-production
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Web
      dockerfile: Dockerfile.production