version: "3.9"

services:
  api:
    image: rolandomalena/moneytrackr:api-staging
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Api
  web:
    image: rolandomalena/moneytrackr:web-staging
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Web