version: "3.9"

services:
  api:
    build:
      context: ./MoneyTrackr/MoneyTrackr.Api
    container_name: moneytrackr-api-production
    ports:
      - 8091:80
  web:
    build:
      context: ./MoneyTrackr/MoneyTrackr.Web
    depends_on:
      - api
    container_name: moneytrackr-web-production
    ports:
      - 8092:80