version: "3.9"

services:
  api:
    image: rolandomalena/moneytrackr:api-production
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Api
  web:
    image: rolandomalena/moneytrackr:web-production
    build:
      context: ./MoneyTrackr/Apps/MoneyTrackr.Web