version: "3.9"

services:
  api-staging:
    build:
      context: ./MoneyTrackr/MoneyTrackr.Api
    container_name: moneytrackr-api-staging
    ports:
      - 8081:80
  web-staging:
    build:
      context: ./MoneyTrackr/MoneyTrackr.Web
    depends_on:
      - api-staging
    container_name: moneytrackr-web-staging
    ports:
      - 8082:80