name: CI/CD

on:
  push:
    branches:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arrays: [{
          name: "Deploy API to Staging",
          app: "api",
          environment: "staging",
          port: 8081,
          shouldRun: "${{ github.ref == 'refs/heads/master' }}"
        }, {
          name: "Deploy Web App to Staging",
          app: "web",
          environment: "staging",
          port: 8082,
          shouldRun: "${{ github.ref == 'refs/heads/master' }}"
        }, {
          name: "Deploy API to Production",
          app: "api",
          environment: "production",
          port: 8091,
          shouldRun: "${{ github.ref == 'refs/heads/production' }}"
        }, {
          name: "Deploy API to Production",
          app: "web",
          environment: "production",
          port: 8092,
          shouldRun: "${{ github.ref == 'refs/heads/production' }}"
        }]
        exclude:
          - arrays: { shouldRun: false }
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production' }}
    steps:
      - name: Download source code
        uses: actions/checkout@v2

      - name: Build common container
        run: docker-compose -f docker-compose-${{ matrix.arrays.environment }}.yml build common
      
      - name: Build container
        run: docker-compose -f docker-compose-${{ matrix.arrays.environment }}.yml build ${{ matrix.arrays.app }}

      - name: Push container
        run: |
          docker login -u rolandomalena -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push rolandomalena/moneytrackr:${{ matrix.arrays.app }}-${{ matrix.arrays.environment }}
      
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker login -u rolandomalena -p '${{ secrets.DOCKERHUB_PASSWORD }}'

            echo Deploying
            sudo docker rm moneytrackr-${{ matrix.arrays.app }}-${{ matrix.arrays.environment }} -f
            sudo docker rmi rolandomalena/moneytrackr:${{ matrix.arrays.app }}-${{ matrix.arrays.environment }} -f
            sudo docker pull rolandomalena/moneytrackr:${{ matrix.arrays.app }}-${{ matrix.arrays.environment }}
            sudo docker run -d -p ${{ matrix.arrays.port }}:80 --restart unless-stopped --name moneytrackr-${{ matrix.arrays.app }}-${{ matrix.arrays.environment }} rolandomalena/moneytrackr:${{ matrix.arrays.app }}-${{ matrix.arrays.environment }}

            echo Cleaning up
            sudo docker container prune -f
            sudo docker image prune -f