name: CI/CD

on:
  push:
    branches:
    - '*'

jobs:
  deploy-staging:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo Downloading source code
            cd deploy
            mkdir ${{ github.sha }}
            cd ${{ github.sha }}
            git clone https://github.com/RolandoMalena/moneytrackr.git
            cd moneytrackr
            git switch ${{ github.ref_name }}

            echo Deploying web api
            cd MoneyTrackr/MoneyTrackr.Api
            sudo docker stop moneytrackr-api-staging
            sudo docker build -t moneytrackr-api-staging . 
            sudo docker run -d -p 8081:80 moneytrackr-api-staging

            echo Deploying web application
            cd ../MoneyTrackr.Web
            sudo docker stop moneytrackr-web-staging
            sudo docker build -t moneytrackr-web-staging . 
            sudo docker run -d -p 8082:80 moneytrackr-web-staging

            echo Cleaning up
            cd ../../../../
            rm ${{ github.sha }} -R -f
            sudo docker container prune -f
            sudo docker image prune -f
  
  deploy-production:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/production' }}
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo Downloading source code
            cd deploy
            mkdir ${{ github.sha }}
            cd ${{ github.sha }}
            git clone https://github.com/RolandoMalena/moneytrackr.git
            cd moneytrackr
            git switch ${{ github.ref_name }}

            echo Deploying web api
            cd MoneyTrackr/MoneyTrackr.Api
            sudo docker stop moneytrackr-api-production
            sudo docker build -t moneytrackr-api-production . 
            sudo docker run -d -p 8091:80 moneytrackr-api-production

            echo Deploying web application
            cd ../MoneyTrackr.Web
            sudo docker stop moneytrackr-web-production
            sudo docker build -t moneytrackr-web-production . 
            sudo docker run -d -p 8092:80 moneytrackr-web-production

            echo Cleaning up
            cd ../../../../
            rm ${{ github.sha }} -R -f
            sudo docker container prune -f
            sudo docker image prune -f