name: CI/CD

on:
  push:
    branches:
    - '*'

jobs:
  deploy-staging:
    runs-on: ubuntu-20.04
    # if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo Downloading source code
            cd deploy
            git clone https://github.com/RolandoMalena/moneytrackr.git
            git checkout ${{ github.ref }}

            echo Deploying...
            cd moneytrackr/MoneyTrackr/MoneyTrackr.Web
            sudo docker stop moneytrackr-staging
            sudo docker build -t moneytrackr-staging . 
            sudo docker run -p 8081:80 moneytrackr-staging

            echo Cleanup
            sudo docker container prune -f
            sudo docker image prune -f